//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQ_AC_Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQ_AC_Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***CLASS^*LVL^AC_CAP^SOFT_CAP_MULTIPLIER^
        ///1^1^312^.35^
        ///1^2^314^.35^
        ///1^3^316^.35^
        ///1^4^318^.35^
        ///1^5^320^.35^
        ///1^6^322^.35^
        ///1^7^324^.35^
        ///1^8^326^.35^
        ///1^9^328^.35^
        ///1^10^330^.35^
        ///1^11^332^.35^
        ///1^12^334^.35^
        ///1^13^336^.35^
        ///1^14^338^.35^
        ///1^15^340^.35^
        ///1^16^342^.35^
        ///1^17^344^.35^
        ///1^18^346^.35^
        ///1^19^348^.35^
        ///1^20^350^.35^
        ///1^21^352^.35^
        ///1^22^354^.35^
        ///1^23^356^.35^
        ///1^24^358^.35^
        ///1^25^360^.35^
        ///1^26^362^.35^
        ///1^27^364^.35^
        ///1^28^366^.35^
        ///1^29^368^.35^
        ///1^30^370^.35^
        ///1^31^372^.35^
        ///1^32^374^.35^ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACMitigation {
            get {
                return ResourceManager.GetString("ACMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown
        ///Warrior
        ///Cleric
        ///Paladin
        ///Ranger
        ///ShadowKnight
        ///Druid
        ///Monk
        ///Bard
        ///Rogue
        ///Shaman
        ///Necromancer
        ///Wizard
        ///Magician
        ///Enchanter
        ///Beastlord
        ///Berserker.
        /// </summary>
        internal static string PlayerClasses {
            get {
                return ResourceManager.GetString("PlayerClasses", resourceCulture);
            }
        }
    }
}
